### PR TITLE
Scraper tests

### PR DESCRIPTION
**Pull request by EdwardChristian**
Writing scraper tests for the Playwright paper scraping feature.

### CODE REVIEW

**Comment by EdwardChristian** [comment]
https://www.scrapingbee.com/webscraping-questions/playwright/how-to-load-local-files-in-playwright/

this might be a way of testing the scraping in Playwright, with jest, but it is currently extremely slow and it impedes testing..

**Comment by EdwardChristian** [comment]
Current bug with Jest, and workaround here:
https://stackoverflow.com/questions/55272295/using-jest-with-puppeteer-evaluation-failed-referenceerror-cov-4kq3tptqc-is

https://github.com/istanbuljs/nyc/issues/514

**Review by jamesgeer — CHANGES_REQUESTED** [review]
- [ ] Write test for a successful POST
- [ ] Replace custom Prisma queries with existing methods, for example:

```
const insertResult = await insertPaper(myPaper);
const getResult = await getPaper(myPaper.id);
expect(insertResult.title).toEqual(getResult.title);
```

Instead of:

```
let testRes: Paper | null = await prisma.paper.findFirst({
				where: {
					source: 'acm',
				},
			});
```

**Review by jamesgeer — APPROVED** [review]
Gordon Ramsay Brilliant

**Pull request merged**
